apiVersion: v1
kind: Service
metadata:
  name: tom-project-service
  namespace: default
spec:
  selector:
    app: tom-project
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080  
  type: LoadBalancer
