apiVersion: v1
kind: ConfigMap
metadata:
  name: mongodb-config
  namespace: mongodb
data:
  mongod.conf: |
    storage:
      dbPath: /data/db
    systemLog:
      destination: file
      logAppend: true
      path: /data/db/mongodb.log
    net:
      bindIp: 0.0.0.0
      port: 27017
