apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-mongodb-data
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: gp2
  hostPath:
    path: /mnt/data/mongodb
